import type { ReactNode } from 'react';
import './globals.css';

export const metadata = {
  title: 'React Project',
  description: 'Generated by Open Design',
};

export default function RootLayout({ children }: { children: ReactNode }) {
  return (
    <html lang="en">
      <body>{children}</body>
    </html>
  );
}
