/**
 * Analyzer for the A2UI generation-consistency measurement.
 *
 * Reads what `collect.ts` wrote and computes the three numbers from
 * `docs/posicube/status.md` "Next #1"/"#3":
 *
 *   1. first-attempt gate pass rate   — does the generator produce valid specs?
 *   2. skeleton agreement rate        — does a fixed catalog remove variance?
 *   3. ceiling collisions             — how often does the agent route around
 *                                       the catalog (contract edits / stray tsx)?
 *
 * Metric 1 is validated against the PRISTINE seed's gate, never the project's
 * own copy. If a run edited `src/authoring/**`, validating with the edited gate
 * would pass by construction — that is exactly the drift recorded in status.md
 * (2026-07-30). The gate must come from outside the agent's workspace, so this
 * script stages a validator sandbox from the seed and runs every spec there.
 *
 * Usage:
 *   pnpm exec tsx scripts/posicube/a2ui-measure/analyze.ts --in .tmp/a2ui-measure/<brief>
 */

import { execFileSync } from "node:child_process";
import { cpSync, existsSync, mkdirSync, readFileSync, writeFileSync } from "node:fs";
import path from "node:path";

import type { FileDelta, IterationRecord } from "./collect.ts";

const repoRoot = path.resolve(import.meta.dirname, "../../..");
const tsxBin = path.join(repoRoot, "node_modules/.bin/tsx");
/** Pinned to the seed's own zod so the gate behaves identically. */
const ZOD_VERSION = "4.4.3";

type Session = {
  briefId: string;
  briefKind: string;
  briefTitle: string;
  runs: number;
  variant: string;
  designSystem: string;
  seedDir: string;
  retrySuppressed: boolean;
  records: IterationRecord[];
};

type GateVerdict = { file: string; success: boolean; issues: string[] };

function fail(message: string): never {
  console.error(`a2ui-analyze: ${message}`);
  process.exit(1);
}

function parseArgs(argv: readonly string[]): { inDir: string; json: boolean } {
  const flags = new Map<string, string>();
  const booleans = new Set<string>();
  for (let i = 0; i < argv.length; i += 1) {
    const token = argv[i];
    if (token === undefined || !token.startsWith("--")) continue;
    const key = token.slice(2);
    const next = argv[i + 1];
    if (next === undefined || next.startsWith("--")) {
      booleans.add(key);
    } else {
      flags.set(key, next);
      i += 1;
    }
  }
  if (booleans.has("help") || booleans.has("h")) {
    console.log(
      [
        "Compute A2UI consistency metrics from collected artifacts.",
        "",
        "Usage:",
        "  pnpm exec tsx scripts/posicube/a2ui-measure/analyze.ts --in <dir> [--json]",
      ].join("\n"),
    );
    process.exit(0);
  }
  const inDir = flags.get("in");
  if (inDir === undefined) fail("--in <dir> is required (the collect.ts --out directory)");
  return { inDir: path.resolve(inDir), json: booleans.has("json") };
}

/**
 * Stage a gate that lives outside any agent's reach.
 *
 * `src/authoring/` is self-contained (spec-schema.ts, catalog.ts, and one JSON
 * of extracted theme enums), so copying that directory plus zod is the whole
 * dependency closure. tsx runs it because the catalog's JSON import is written
 * bundler-style, without an import attribute.
 */
function prepareValidator(seedDir: string): string {
  const validatorDir = path.join(repoRoot, ".tmp/a2ui-measure/validator");
  const authoringSource = path.join(repoRoot, seedDir, "src/authoring");
  if (!existsSync(authoringSource)) {
    fail(`seed authoring dir not found: ${authoringSource}`);
  }

  mkdirSync(validatorDir, { recursive: true });
  cpSync(authoringSource, path.join(validatorDir, "authoring"), { recursive: true });
  writeFileSync(
    path.join(validatorDir, "package.json"),
    `${JSON.stringify(
      {
        name: "a2ui-measure-validator",
        private: true,
        type: "module",
        dependencies: { zod: ZOD_VERSION },
      },
      null,
      2,
    )}\n`,
  );
  writeFileSync(
    path.join(validatorDir, "validate.ts"),
    `${[
      "// Generated by scripts/posicube/a2ui-measure/analyze.ts — do not edit.",
      'import { readFileSync } from "node:fs";',
      "",
      'import { validateSpec } from "./authoring/spec-schema.ts";',
      "",
      "const results = process.argv.slice(2).map((file) => {",
      "  try {",
      '    const parsed = validateSpec(JSON.parse(readFileSync(file, "utf8")));',
      "    if (parsed.success) return { file, success: true, issues: [] };",
      "    const issues = parsed.error.issues",
      "      .slice(0, 5)",
      '      .map((issue) => `${issue.path.join(".") || "<root>"}: ${issue.message}`);',
      "    return { file, success: false, issues };",
      "  } catch (err) {",
      "    const message = err instanceof Error ? err.message : String(err);",
      "    return { file, success: false, issues: [`unreadable: ${message}`] };",
      "  }",
      "});",
      "console.log(JSON.stringify(results));",
    ].join("\n")}\n`,
  );

  if (!existsSync(path.join(validatorDir, "node_modules/zod"))) {
    console.log(`a2ui-analyze: installing zod@${ZOD_VERSION} into the validator sandbox…`);
    try {
      execFileSync("npm", ["install", "--silent", "--no-audit", "--no-fund"], {
        cwd: validatorDir,
        stdio: "inherit",
      });
    } catch (err) {
      fail(`validator npm install failed: ${err instanceof Error ? err.message : String(err)}`);
    }
  }
  return validatorDir;
}

function runGate(validatorDir: string, specPaths: readonly string[]): Map<string, GateVerdict> {
  const verdicts = new Map<string, GateVerdict>();
  if (specPaths.length === 0) return verdicts;
  if (!existsSync(tsxBin)) fail(`tsx not found at ${tsxBin} — run pnpm install`);

  const stdout = execFileSync(
    tsxBin,
    [path.join(validatorDir, "validate.ts"), ...specPaths],
    { cwd: validatorDir, encoding: "utf8", maxBuffer: 32 * 1024 * 1024 },
  );
  const parsed: unknown = JSON.parse(stdout.trim().split("\n").at(-1) ?? "[]");
  if (!Array.isArray(parsed)) fail("validator returned a non-array result");
  for (const entry of parsed as GateVerdict[]) {
    verdicts.set(entry.file, entry);
  }
  return verdicts;
}

/**
 * The screen's top-level shape: the block types directly under `root`, in order.
 *
 * This is the consistency signal. Two runs of the same brief that both produce
 * `Page → [PageHeader, StatCardRow, Chart, DataTable]` agree even if every
 * label and prop differs; a fixed catalog is supposed to make that the norm.
 */
function skeletonOf(specFile: string): string | null {
  try {
    const spec: unknown = JSON.parse(readFileSync(specFile, "utf8"));
    if (spec === null || typeof spec !== "object") return null;
    const record = spec as { root?: unknown; nodes?: unknown };
    if (typeof record.root !== "string" || !Array.isArray(record.nodes)) return null;
    const byId = new Map<string, { type?: unknown; children?: unknown }>();
    for (const node of record.nodes as { id?: unknown }[]) {
      if (node !== null && typeof node === "object" && typeof node.id === "string") {
        byId.set(node.id, node as { type?: unknown; children?: unknown });
      }
    }
    const rootNode = byId.get(record.root);
    if (rootNode === undefined || !Array.isArray(rootNode.children)) return null;
    const types = (rootNode.children as unknown[]).map((childId) => {
      if (typeof childId !== "string") return "?";
      const child = byId.get(childId);
      return typeof child?.type === "string" ? child.type : "?";
    });
    return types.join(" → ");
  } catch {
    return null;
  }
}

function percent(part: number, whole: number): string {
  if (whole === 0) return "n/a";
  return `${((part / whole) * 100).toFixed(0)}% (${part}/${whole})`;
}

function tallyDeltas(records: readonly IterationRecord[]): Map<string, number> {
  const counts = new Map<string, number>();
  const bump = (key: string): void => {
    counts.set(key, (counts.get(key) ?? 0) + 1);
  };
  for (const record of records) {
    for (const delta of record.contractEdits as FileDelta[]) bump(`${delta.status} ${delta.file}`);
    for (const file of record.extraSourceFiles) bump(`extra ${file}`);
  }
  return counts;
}

function main(): void {
  const { inDir, json } = parseArgs(process.argv.slice(2));
  const sessionPath = path.join(inDir, "session.json");
  if (!existsSync(sessionPath)) fail(`no session.json under ${inDir} — did collect.ts finish?`);
  const session = JSON.parse(readFileSync(sessionPath, "utf8")) as Session;

  const validatorDir = prepareValidator(session.seedDir);

  const specPaths: string[] = [];
  const specByIndex = new Map<number, string>();
  for (const record of session.records) {
    const specPath = path.join(
      inDir,
      "runs",
      String(record.index).padStart(3, "0"),
      "a2ui-spec.json",
    );
    if (record.specWritten && existsSync(specPath)) {
      specPaths.push(specPath);
      specByIndex.set(record.index, specPath);
    }
  }

  const verdicts = runGate(validatorDir, specPaths);

  const total = session.records.length;
  const withSpec = specPaths.length;
  let gatePassed = 0;
  const skeletons = new Map<string, number>();
  const perRun: {
    index: number;
    specWritten: boolean;
    gatePass: boolean;
    issues: string[];
    skeleton: string | null;
    contractEdits: number;
    extraSourceFiles: number;
  }[] = [];

  for (const record of session.records) {
    const specPath = specByIndex.get(record.index);
    const verdict = specPath === undefined ? undefined : verdicts.get(specPath);
    const gatePass = verdict?.success === true;
    if (gatePass) gatePassed += 1;
    const skeleton = specPath === undefined ? null : skeletonOf(specPath);
    if (skeleton !== null) skeletons.set(skeleton, (skeletons.get(skeleton) ?? 0) + 1);
    perRun.push({
      index: record.index,
      specWritten: record.specWritten,
      gatePass,
      issues: verdict?.issues ?? [],
      skeleton,
      contractEdits: record.contractEdits.length,
      extraSourceFiles: record.extraSourceFiles.length,
    });
  }

  const rankedSkeletons = [...skeletons.entries()].sort((a, b) => b[1] - a[1]);
  const modal = rankedSkeletons[0];
  const skeletonTotal = [...skeletons.values()].reduce((sum, n) => sum + n, 0);
  const contractRuns = session.records.filter((r) => r.contractEdits.length > 0).length;
  const extraRuns = session.records.filter((r) => r.extraSourceFiles.length > 0).length;
  const ceilingRuns = session.records.filter(
    (r) => r.contractEdits.length > 0 || r.extraSourceFiles.length > 0,
  ).length;

  if (json) {
    console.log(
      JSON.stringify(
        {
          brief: { id: session.briefId, kind: session.briefKind, title: session.briefTitle },
          variant: session.variant,
          designSystem: session.designSystem,
          retrySuppressed: session.retrySuppressed,
          total,
          specWritten: withSpec,
          gatePassed,
          skeletons: rankedSkeletons.map(([shape, count]) => ({ shape, count })),
          ceiling: { contractRuns, extraRuns, ceilingRuns },
          perRun,
        },
        null,
        2,
      ),
    );
    return;
  }

  const warn = session.retrySuppressed ? "" : "  ⚠️ retries were ALLOWED — not a first-attempt rate";
  console.log(`\nA2UI measurement — ${session.briefTitle} (${session.briefId}, kind ${session.briefKind})`);
  console.log(`  variant=${session.variant}  design-system=${session.designSystem}  n=${total}${warn}\n`);

  console.log("① 스펙 생성 / 게이트");
  console.log(`   스펙을 썼는가        ${percent(withSpec, total)}`);
  console.log(`   게이트 통과 (스펙 중) ${percent(gatePassed, withSpec)}`);
  console.log(`   게이트 통과 (전체)    ${percent(gatePassed, total)}`);

  console.log("\n② 스켈레톤 일관성  (root 직계 자식 타입 순서)");
  if (modal === undefined) {
    console.log("   측정 불가 — 파싱 가능한 스펙이 없습니다.");
  } else {
    console.log(`   최빈 스켈레톤 점유율 ${percent(modal[1], skeletonTotal)}`);
    console.log(`   서로 다른 스켈레톤   ${rankedSkeletons.length}종`);
    for (const [shape, count] of rankedSkeletons) {
      console.log(`     ${String(count).padStart(3)}×  ${shape}`);
    }
  }

  console.log("\n③ 천장 충돌  (에이전트가 카탈로그를 우회한 횟수)");
  console.log(`   계약 파일 수정       ${percent(contractRuns, total)}`);
  console.log(`   여분 .tsx 생성       ${percent(extraRuns, total)}`);
  console.log(`   둘 중 하나라도       ${percent(ceilingRuns, total)}`);
  const tally = tallyDeltas(session.records);
  if (tally.size > 0) {
    console.log("   빈발 항목 (카탈로그 확장 후보):");
    for (const [key, count] of [...tally.entries()].sort((a, b) => b[1] - a[1]).slice(0, 12)) {
      console.log(`     ${String(count).padStart(3)}×  ${key}`);
    }
  }

  const failures = perRun.filter((r) => r.specWritten && !r.gatePass);
  if (failures.length > 0) {
    console.log("\n게이트 실패 상세");
    for (const failure of failures) {
      console.log(`   run ${String(failure.index).padStart(3)}: ${failure.issues.join(" | ") || "(no issues reported)"}`);
    }
  }
  console.log("");
}

main();
